root: true
owner: CERN & UNCONVENTIONAL
start_year: 2023
template: |-
  {comment_start} This file is part of Flask-Multipass-Keycloak.
  {comment_middle} Copyright (C) {dates} {owner}
  {comment_end}
